'use client';

import { CircleDollarSign, Package, ShoppingCart, Store, UserRound, AlertTriangle } from 'lucide-react';
import { DashboardShell, commonAdminNav } from '@/components/DashboardShell';
import { products } from '@/app/data';
import '../dashboard.css';

export default function AdminDashboard() {
  return <DashboardShell role="admin" title="Good morning, team" subtitle="A pulse check on everything happening across Bazzaro." nav={commonAdminNav}>
    <div className="dashboard-stat-grid"><Stat label="Total sales" value="Rs. 4.82m" change="↑ 16.8% this month" icon={<CircleDollarSign size={15} />} /><Stat label="Orders this month" value="2,486" change="↑ 9.4% vs last month" icon={<ShoppingCart size={15} />} /><Stat label="Active customers" value="18,204" change="↑ 12.1% this month" icon={<UserRound size={15} />} /><Stat label="Platform commission" value="Rs. 482k" change="↑ 15.7% this month" icon={<Store size={15} />} /></div>
    <div className="dashboard-chart-grid"><section className="dashboard-panel"><div className="dashboard-panel-header"><div><h2>Marketplace revenue</h2><p>Gross merchandise value across all sellers</p></div><select className="panel-select" defaultValue="30"><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div><RevenueChart /></section><section className="dashboard-panel"><div className="dashboard-panel-header"><div><h2>Sales by category</h2><p>Where customers are shopping</p></div></div><div className="donut-wrap"><div className="donut" /><div className="chart-legend"><span><i className="legend-dot" /> Fashion · 46%</span><span><i className="legend-dot two" /> Home · 26%</span><span><i className="legend-dot three" /> Tech · 17%</span><span><i className="legend-dot four" /> Other · 11%</span></div></div></section></div>
    <section className="dashboard-panel dashboard-table-panel"><div className="dashboard-panel-header"><div><h2>Needs your attention</h2><p>Keep the marketplace moving smoothly</p></div><button className="dashboard-light-button">View all tasks</button></div><table className="dashboard-table"><thead><tr><th>Type</th><th>Subject</th><th>Created</th><th>Owner</th><th>Status</th></tr></thead><tbody><AdminRow icon={<Store size={14} />} subject="Vendor approval · Mero Mitho" detail="New vendor application" date="Today, 11:04 AM" owner="Vendor team" status="Review" statusClass="orange" /><AdminRow icon={<Package size={14} />} subject="Product approval · 12 items" detail="Awaiting content review" date="Today, 10:32 AM" owner="Product team" status="Pending" statusClass="orange" /><AdminRow icon={<CircleDollarSign size={14} />} subject="Withdrawal · Rs. 84,500" detail="Sajilo Goods" date="Yesterday" owner="Finance team" status="Review" statusClass="orange" /><AdminRow icon={<AlertTriangle size={14} />} subject="Low stock alert · 18 products" detail="Across 9 sellers" date="Yesterday" owner="Inventory" status="Open" statusClass="gray" /></tbody></table></section>
    <section className="dashboard-panel dashboard-table-panel"><div className="dashboard-panel-header"><div><h2>Top products this month</h2><p>Best performers across the marketplace</p></div><a className="dashboard-mini-link" href="#products">Full catalogue →</a></div><table className="dashboard-table"><thead><tr><th>Product</th><th>Seller</th><th>Category</th><th>Units sold</th><th>Revenue</th></tr></thead><tbody><TopProduct product={products[0]} seller="Himalayan Carry Co." units="482" revenue="Rs. 1.39m" /><TopProduct product={products[2]} seller="Kalo Studio" units="361" revenue="Rs. 1.51m" /><TopProduct product={products[5]} seller="Nourish Lab Nepal" units="308" revenue="Rs. 385k" /></tbody></table></section>
  </DashboardShell>;
}
function Stat({ label, value, change, icon }: { label: string; value: string; change: string; icon: React.ReactNode }) { return <div className="dashboard-stat-card"><span>{label}</span><strong>{value}</strong><small className="stat-change">{change}</small><i className="stat-icon">{icon}</i></div>; }
function RevenueChart() { return <div className="fake-chart"><div className="chart-lines"><span /><span /><span /><span /><span /></div><div className="chart-y-labels"><span>1.0m</span><span>750k</span><span>500k</span><span>250k</span><span>0</span></div><svg className="chart-svg" viewBox="0 0 700 160" preserveAspectRatio="none"><defs><linearGradient id="fillAdmin" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e9623d" stopOpacity=".23" /><stop offset="1" stopColor="#e9623d" stopOpacity="0" /></linearGradient></defs><path d="M0 139 C45 120 63 112 94 124 S140 87 178 103 S225 109 259 84 S309 99 342 69 S392 85 423 62 S477 73 508 45 S555 71 590 37 S645 47 700 18 V160 H0 Z" fill="url(#fillAdmin)" /><path d="M0 139 C45 120 63 112 94 124 S140 87 178 103 S225 109 259 84 S309 99 342 69 S392 85 423 62 S477 73 508 45 S555 71 590 37 S645 47 700 18" fill="none" stroke="#e9623d" strokeWidth="2.5" /></svg><div className="chart-x-labels"><span>01 Sep</span><span>07 Sep</span><span>14 Sep</span><span>21 Sep</span><span>Today</span></div></div>; }
function AdminRow({ icon, subject, detail, date, owner, status, statusClass }: { icon: React.ReactNode; subject: string; detail: string; date: string; owner: string; status: string; statusClass: string }) { return <tr><td><span className="table-type-icon">{icon}</span></td><td className="table-product"><div><strong>{subject}</strong><small>{detail}</small></div></td><td>{date}</td><td>{owner}</td><td><span className={`status-pill ${statusClass}`}>{status}</span></td></tr>; }
function TopProduct({ product, seller, units, revenue }: { product: typeof products[number]; seller: string; units: string; revenue: string }) { return <tr><td className="table-product"><img src={product.image} alt="" className="table-thumb" /><strong>{product.name}</strong></td><td>{seller}</td><td>{product.category}</td><td>{units}</td><td><strong>{revenue}</strong></td></tr>; }
