'use client';

import Link from 'next/link';
import { ArrowLeft, Bell, ChevronRight, Heart, MapPin, Package, RotateCcw, Settings, ShieldCheck, UserRound } from 'lucide-react';
import { products } from '@/app/data';
import '../dashboard.css';
import '../account.css';

export default function AccountPage() {
  return <div className="account-page"><header className="account-header"><Link className="brand" href="/"><span className="brand-mark"><span /><span /><span /><span /></span><span>bazzaro</span></Link><Link href="/" className="account-back"><ArrowLeft size={15} /> Back to shopping</Link></header><main className="account-main"><div className="account-welcome"><span className="account-large-avatar">SG</span><div><span className="eyebrow">Your Bazzaro account</span><h1>Hello, Sudeep.</h1><p>Member since September 2025 · Kathmandu Valley</p></div><button className="account-edit"><Settings size={15} /> Edit profile</button></div><div className="account-summary"><div><Package size={18} /><span><strong>3</strong><small>Orders</small></span></div><div><Heart size={18} /><span><strong>8</strong><small>Saved finds</small></span></div><div><MapPin size={18} /><span><strong>2</strong><small>Addresses</small></span></div><div><ShieldCheck size={18} /><span><strong>Good</strong><small>Account health</small></span></div></div><div className="account-grid"><section className="account-orders"><div className="account-section-head"><div><span className="eyebrow">Recent activity</span><h2>Your orders</h2></div><button>View all <ChevronRight size={14} /></button></div><OrderCard image={products[2].image} name="Cloudstep Knit Sneakers" order="#BZ-10461" status="Delivered on 22 Sep" statusClass="green" /><OrderCard image={products[0].image} name="Sajilo Everyday Backpack" order="#BZ-10384" status="On the way · Arrives tomorrow" statusClass="orange" /></section><aside className="account-side"><div className="account-side-card"><div className="account-section-head"><div><span className="eyebrow">Saved for later</span><h2>Your finds</h2></div><Heart size={17} /></div><div className="saved-row">{products.slice(0, 3).map((product) => <div key={product.id}><img src={product.image} alt={product.name} /><span>{product.name}</span></div>)}</div><Link href="/#just-in" className="account-side-link">See all saved finds <ChevronRight size={14} /></Link></div><div className="account-help"><Bell size={18} /><div><strong>Need a hand?</strong><p>We&apos;re here Mon–Fri, 10am–6pm.</p><button>Visit help centre →</button></div></div></aside></div><div className="account-links"><Link href="#"><UserRound size={17} /><span><strong>Profile details</strong><small>Manage your personal details</small></span><ChevronRight size={15} /></Link><Link href="#"><MapPin size={17} /><span><strong>Addresses</strong><small>Manage delivery addresses</small></span><ChevronRight size={15} /></Link><Link href="#"><RotateCcw size={17} /><span><strong>Returns & refunds</strong><small>Track your returns</small></span><ChevronRight size={15} /></Link></div></main></div>;
}
function OrderCard({ image, name, order, status, statusClass }: { image: string; name: string; order: string; status: string; statusClass: string }) { return <div className="account-order-card"><img src={image} alt="" /><div><span className="account-order-id">{order}</span><h3>{name}</h3><span className={`status-pill ${statusClass}`}>{status}</span></div><button>View order <ChevronRight size={14} /></button></div>; }
